rmdir /s /q c:\wamp\www\UP\example\vendor\uphp\action-controller
rmdir /s /q c:\wamp\www\UP\example\vendor\uphp\exception
rmdir /s /q c:\wamp\www\UP\example\vendor\uphp\framework
rmdir /s /q c:\wamp\www\UP\example\vendor\uphp\helpers
rmdir /s /q c:\wamp\www\UP\example\vendor\uphp\inflection
rmdir /s /q c:\wamp\www\UP\example\vendor\uphp\routes
rmdir /s /q c:\wamp\www\UP\example\vendor\uphp\action-view
rmdir /s /q c:\wamp\www\UP\example\vendor\uphp\languages
rmdir /s /q c:\wamp\www\UP\example\vendor\uphp\ORM
mklink /d c:\wamp\www\UP\example\vendor\uphp\action-controller c:\wamp\www\UP\uphp\action-controller
mklink /d c:\wamp\www\UP\example\vendor\uphp\exception c:\wamp\www\UP\uphp\exception
mklink /d c:\wamp\www\UP\example\vendor\uphp\framework c:\wamp\www\UP\uphp\framework
mklink /d c:\wamp\www\UP\example\vendor\uphp\helpers c:\wamp\www\UP\uphp\helpers
mklink /d c:\wamp\www\UP\example\vendor\uphp\inflection c:\wamp\www\UP\uphp\inflection
mklink /d c:\wamp\www\UP\example\vendor\uphp\routes c:\wamp\www\UP\uphp\routes
mklink /d c:\wamp\www\UP\example\vendor\uphp\action-view c:\wamp\www\UP\uphp\action-view
mklink /d c:\wamp\www\UP\example\vendor\uphp\languages c:\wamp\www\UP\uphp\languages
mklink /d c:\wamp\www\UP\example\vendor\uphp\ORM c:\wamp\www\UP\uphp\ORM